apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-native-overview-config
  labels:
    app: spring-native-overview
data:
  spring.datasource.url: jdbc:h2:mem:testdb
  spring.datasource.username: sa
  spring.datasource.password: password
