apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-native-overview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-native-overview
  template:
    metadata:
      labels:
        app: spring-native-overview
    spec:
      containers:
        - name: app
          image: spring-native-overview:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: "Never"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          envFrom:
            - configMapRef:
                name: spring-native-overview-config
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: spring-native-overview
spec:
  selector:
    app: spring-native-overview
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
